### ISSUE TITLE
Stuck at "Generating solution..."

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/task-allocation-demo#1]
I created a new project and when I solve this I observe that the backend server finds a solution but the frontend won't show it. It just gets stuck on the "Generating solution..." screen.

This might be an artefact of the static export, but I am not sure.

Also the https://demos.constraintmodelling.org/task-allocation/output screen gives a 404, but clicking on "Solution Details" from the left menu doesn't (even though it rewrites the URL to same).

Any ideas @williamburns ? Or else I might have to learn some next.js :)

**Comment by ozgurakgun** [comment]
Confirmed that the same issue happens locally when run using `npm run start`

**Comment by williamburns** [comment]
@ozgurakgun pretty sure this is to do with static export, since after generating solution i can go back to homepage and then to output page and it works. what has changed since we demoed it? (fyi locked out of uni email if you tried to email me)

**Comment by ozgurakgun** [comment]
Do you want to try locally with this export? This gets stuck for me as well (even though I am not using the static export)
[chores.json.txt](https://github.com/conjure-cp/task-allocation-demo/files/11655612/chores.json.txt)

The only change is this commit which shouldn't change anything https://github.com/conjure-cp/task-allocation-demo/commit/ee353b502c4a8d564be423692379c5897f0b08fb.

Thanks!
